### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by thibaultboursier** [hdorgeval/stargate#1]
Hello Henri,

I didn't manage to clone the repository. It sucks on unpacking objects phase... I deleted 44 mo image (it blocked to 44%), but now cloning is blocked to 94%. I know my connection is not really good, but ... I'm trying to clone again.

Do you have an idea ?

Thanks

**Comment by thibaultboursier** [comment]
Finally, I managed to clone repo but it takes a lot of time...

**Comment by hdorgeval** [comment]
@thibaultboursier,should be fixed in my last commit

**Comment by hdorgeval** [comment]
@thibaultboursier : I moved the animated gif to a separate branch

**Comment by hdorgeval** [comment]
@thibaultboursier : the demo is now playing on the README! But you will not see it in Preview mode inside VS Code
